name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libgl1
      - name: Install python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest scikit-learn
      - name: Run tests
        run: pytest -q